"updates":
- "directory": "/"
  "open-pull-requests-limit": 6
  "package-ecosystem": "cargo"
  "schedule":
    "interval": "daily"
    "time": "01:00"
    "timezone": "America/Los_Angeles"
"version": 2
